DELETE FROM adoption;
DELETE FROM user_preference;
DELETE FROM preference_animal;
DELETE FROM user_animal;
DELETE FROM preference;
DELETE FROM animal;
DELETE FROM user;

INSERT INTO user (id, username, first_name, last_name, email, phone_number, password, role) VALUES (1, 'Dżonek', 'John', 'Doe', 'john.doe@gmail.com', '677888555', 'password123','admin' );
INSERT INTO user (id, username, first_name, last_name, email, phone_number, password, role) VALUES (2, 'Hanusia007', 'Hannah', 'Montana', 'hannah.montana@interia.com', '666333444', 'password321', 'user');
INSERT INTO user (id, username, first_name, last_name, email, phone_number, password, role) VALUES (3, 'Zbyniu02', 'Zbigniew', 'Nowak', 'zbysiu.nowak@gmail.com', '654333222', 'pass322','user'      );
INSERT INTO animal (id, type, name, age, color, status, short_description, image) VALUES (1, 'Pies', 'Reksio', 3, 'Brązowy', 'Dostępny', 'Śpioszek, lubi się tulić', 'https://ocdn.eu/pulscms-transforms/1/IEdk9kpTURBXy8yZDY5MTU1ZThmZGY4NWZmOTk3ZTUwOTRkMWI1YjAwMy5qcGeSlQLNA8AAwsOVAgDNA8DCw94AAaEwBg');
INSERT INTO animal (id, type, name, age, color, status, short_description, image) VALUES (2, 'Pies', 'Lily', 1, 'Brązowy', 'Dostępny', 'Prawdziwy model, dystyngowany', 'https://ocdn.eu/pulscms-transforms/1/B3tk9kpTURBXy9hMTZmOGFmZWU0ZTI2NjE4Y2FiYTE3Yzc2ZWQzOWFkMi5qcGeSkwXNAxTNAbyTCaZmZWFhZmUG3gABoTAG/shutterstock-8050477.avif');
INSERT INTO animal (id, type, name, age, color, status, short_description, image) VALUES (3, 'Kot', 'Basia', 5, 'Ruda', 'Zarezerwowana', 'Ma charakterek, kocia dama', 'https://zwierzakinadpotokiem.pl/wp-content/uploads/2023/12/kot.jpg');
INSERT INTO animal (id, type, name, age, color, status, short_description, image) VALUES (4, 'Kot', 'Mietek', 6, 'Brązowy', 'Dostępny', 'Głośno mruczy', 'https://upload.wikimedia.org/wikipedia/commons/7/76/WPKiW_-_ZOO_-_Nied%C5%BAwied%C5%BA_Brunatny.JPG');
INSERT INTO animal (id, type, name, age, color, status, short_description, image) VALUES (5, 'Papuga', 'Mimi', 3, 'Kolorowa', 'Dostępna', 'Zna dużo słów, nie przeklina', 'https://zwierzakinadpotokiem.pl/wp-content/uploads/2023/12/papuga-amazonka.jpg');
INSERT INTO preference (id, type, color, min_age, max_age) VALUES (1, 'Dog', 'Brown', 1, 5);
INSERT INTO preference (id, type, color, min_age, max_age) VALUES (2, 'Dog', 'Brown', 1, 5);
INSERT INTO adoption (id, adoption_date, user_id, animal_id) VALUES (1, '2024-06-25', 1, 1);
INSERT INTO user_animal (user_id, animal_id) VALUES (3, 1);
INSERT INTO user_animal (user_id, animal_id) VALUES (3, 3);
INSERT INTO user_animal (user_id, animal_id) VALUES (3, 5);
